###Get all
Get http://localhost:3000/user 
###Get all comments
Get http://localhost:3000/comments
### tables
Get http://localhost:3000/tables
### reservations
Get http://localhost:3000/reservations
### get by id user
GET http://localhost:3000/user/67acdfe1b7b06c6425c5165d
### get by id comment
GET http://localhost:3000/comments/67a24f55a83aa72970dbde6f
### get by id table
GET http://localhost:3000/tables/67a24f2ba83aa72970dbde6e
### get by id reservation
GET http://localhost:3000/reservations/67ae341713801e7aa9836f33















### create user
POST http://localhost:3000/user HTTP/1.1
Content-Type: application/json
{
    "name": "John",
    "lastname": "Doe",
    "email": "john.doe@example.com",
    "phone": "123456789"
}
### create comment
POST http://localhost:3000/comments HTTP/1.1
Content-Type: application/json
{
    "name": "Jhon",
    "rating": 5,
    "text": "Excellent service and delicious food."
}
### create table
POST http://localhost:3000/tables HTTP/1.1
Content-Type: application/json
{
    "tableNumber": 1,
    "capacity": 4,
    "location": "indoor",
    "status": "available"
}
### create reservation
POST http://localhost:3000/reservations HTTP/1.1
Content-Type: application/json
{
    "name": "Jhon",
    "reservationDate": "2023-10-15",
    "numberOfPeople": 45,
    "notes": "Table near the window"

}

#########################################################################################################################3333
### update user
PUT http://localhost:3000/user/679456d68ef015110ba2c91b HTTP/1.1
Content-Type: application/json
{
    "name": "John",
    "lastname": "Doe",
    "email": "john.doe@example.com",
    "phone": "123456789"
}
### update comment
PUT http://localhost:3000/comments/679456d68ef015110ba2c91b HTTP/1.1
Content-Type: application/json
{
    "name": "Jhon",
    "rating": 5,
    "text": "Excellent service and delicious food."
}
### update table
PUT http://localhost:3000/tables/679456d68ef015110ba2c91b HTTP/1.1
Content-Type: application/json
{
    "tableNumber": 1,
    "capacity": 4,
    "location": "indoor",
    "status": "available"
}
### update reservation
PUT http://localhost:3000/reservations/679456d68ef015110ba2c91b HTTP/1.1
Content-Type: application/json
{
    "name": "Jhon",
    "reservationDate": "2023-10-15",
    "numberOfPeople": 45,
    "notes": "Table near the window"
}

#####################################################################################################################################
### Delete a user by Id
DELETE http://localhost:3000/user/679456d68ef015110ba2c91b HTTP/1.1
### Delete a user by Id
DELETE http://localhost:3000/comments/679456d68ef015110ba2c91b HTTP/1.1
### Delete a user by Id
DELETE http://localhost:3000/reservations/679456d68ef015110ba2c91b HTTP/1.1
### Delete a user by Id
DELETE http://localhost:3000/tables/679456d68ef015110ba2c91b HTTP/1.1